<?php

namespace ContainerUoYFyjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ATt_UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._aTt_.U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._aTt_.U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'pc' => ['privates', 'App\\Repository\\ProduitsCategorieRepository', 'getProduitsCategorieRepositoryService', true],
        ], [
            'data' => 'App\\Repository\\ProduitsRepository',
            'pc' => 'App\\Repository\\ProduitsCategorieRepository',
        ]);
    }
}
