<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoYFyjC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoYFyjC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoYFyjC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoYFyjC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoYFyjC\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoYFyjC',
    'container.build_id' => 'b2868538',
    'container.build_time' => 1677162799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoYFyjC');
